version: '3.1'
services:
  core-db:
    image: postgres:15-alpine
    ports:
      - "7778:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  redis:
    image: redis:7-alpine
    ports:
      - "63790:6379"

  env_file: .env